#!/usr/bin/zsh

typeset -gA COLOR_CONFIG_MESSAGES
typeset -gA ACTION_CONFIG_MESSAGES
typeset -gA FILL_CONFIG_MESSAGES

COLOR_CONFIG_MESSAGES[ERROR]="red"
COLOR_CONFIG_MESSAGES[WARNING]="yellow"
COLOR_CONFIG_MESSAGES[INFO]="cyan"
COLOR_CONFIG_MESSAGES[OK]="green"

ACTION_CONFIG_MESSAGES[ERROR]="exit"

FILL_CONFIG_MESSAGES[ERROR]="[-] Error:"
FILL_CONFIG_MESSAGES[OK]="[+] Ok:"
FILL_CONFIG_MESSAGES[WARNING]="[?] Warning:"
FILL_CONFIG_MESSAGES[INFO]="[!] Info:"

function messages {
    autoload -U colors
    hooks "config_hook_messages"
}

function message {
    local rcolor
    local lcolor
    local clr
    local spec
    local level="$1"
    shift
    local msg="$*"
    spec="${level:u}"
    clr=${COLOR_CONFIG_MESSAGES[$spec]}

    lcolor="${fg_bold[$clr]}"
    rcolor="${reset_color}${fg[$clr]}"
    rstcolor="${reset_color}"
    icon=${FILL_CONFIG_MESSAGES[$spec]}

    printf "%b%s%b\t%30b%b\n" $lcolor $icon $rcolor $msg $rstcolor 1>&2
    if [[ ${ACTION_CONFIG_MESSAGES[$spec]} = "exit" ]]; then
	return 1
    fi

}

function error {
    message "Error" "$@"
}
function ok {
    message "Ok" "$@"
}
function warning {
    message "Warning" "$@"
}
function info {
    message "Info" "$@"
}
