#!/usr/bin/zsh 


typeset -i seconds 
typeset -f delta 
typeset -i oldtime
typeset -i newtime 

function delta_time {
        old=$1
        new=$2
        num=$3 
        (( delta = (new - old) / num ))
}

function get_time {
        seconds=$(date +%s)
}

old_num=0
while :;do 
        print $@
        num=$($@)

        (( dt = new_time - old_time ))
        old_time=$new_time 
        delta_time $num $old_num $dt  
        print "$delta/s"
        old_num=$num
        sleep 1 
        get_time 
        new_time=$seconds 
done 

